// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqwndkzvjgdoiiulkjjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xd25ka3p2amdkb2lpdWxrampvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTI1NzAsImV4cCI6MjA2MDY4ODU3MH0.nERPh9ufkC8eZanAh15n2v4Gj6rrZku2udNXtOa0vvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);